### ISSUE TITLE
PDF files do not allow copying from file

### ISSUE THREAD

**Issue by felixbastian** [ksharindam/gospel-pdf-viewer#6]
Hi, I'd love to use your viewer. However, for me it is a deal breaker that I cannot copy the text from the PDF.
Do you have any quick fix for this issue?

**Comment by ksharindam** [comment]
It supports text copying.
Click the copy button in toolbar, then click and drag on page. Text will be
copied.

**Comment by felixbastian** [comment]
That's helpful. Thanks!
