### ISSUE TITLE
source url for quikprint

### ISSUE THREAD

**Issue by lecramyajiv** [ksharindam/gospel-pdf-viewer#7]
When I try to use the print option it says "install quikprint", but I can't seem to find this project 
anywhere. Please post the source url of quikprint. I'm using linux 64-bit.

**Comment by lecramyajiv** [comment]
found the url https://github.com/ksharindam/quikprint

**Comment by ksharindam** [comment]
@lecramyajiv quikprint is not recommened, because it supports only few printers. I have added, native printing support. If quikprint not installed, it opens native print dialog. Try it.

**Comment by lecramyajiv** [comment]
@ksharindam I tried it without quikprint. it opens the dialog and shows the options. But when on
clicking the quit button at the bottom it does not close otherwise it works.
